- name: Uploading PuppetLabs repo file to /etc/yum.repos.d/puppetlabs-pc1.repo
  template: src=puppetlabs-pc1.repo.j2 dest=/etc/yum.repos.d/puppetlabs-pc1.repo

- name: Update Packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Update Hosts File
  template: src=hosts.j2 dest=/etc/hosts

- name: Allow Ports through the firewall
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - 8140

- name: Adding Puppetlabs /bin to bashrc
  command:
    echo export PATH=$PATH:/opt/puppetlabs/bin/ >> .bashrc
